name: .NET
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore "BookingApp.API/BookingApp.API.csproj"
      - name: Build
        run: dotnet build "BookingApp.API/BookingApp.API.csproj"
      - name: Controller Tests
        run: >-
          dotnet test
          "BookingApp.Tests.Controllers/BookingApp.Tests.Controllers.csproj"
          --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
            context: .
            file: ./BookingApp.API/Dockerfile
            tags: sunfiremohawk/booking-app-api:latest,sunfiremohawk/booking-app-api:1.0.0
            target: final