name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "BookingApp.API/BookingApp.API.csproj"
    - name: Build
      run: dotnet build "BookingApp.API/BookingApp.API.csproj"
    - name: Test
      run: dotnet test "BookingApp.Tests.Controllers/BookingApp.Tests.Controllers.csproj" --no-build --verbosity normal
